# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moutaw_i/R-Type2/R-Type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moutaw_i/R-Type2/R-Type

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moutaw_i/R-Type2/R-Type/CMakeFiles /home/moutaw_i/R-Type2/R-Type/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moutaw_i/R-Type2/R-Type/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SNetwork

# Build rule for target.
SNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SNetwork
.PHONY : SNetwork

# fast build rule for target.
SNetwork/fast:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/build
.PHONY : SNetwork/fast

#=============================================================================
# Target rules for targets named Thread

# Build rule for target.
Thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Thread
.PHONY : Thread

# fast build rule for target.
Thread/fast:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/build
.PHONY : Thread/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

lib/SNetwork/src/ATCPClientSocket.o: lib/SNetwork/src/ATCPClientSocket.cpp.o
.PHONY : lib/SNetwork/src/ATCPClientSocket.o

# target to build an object file
lib/SNetwork/src/ATCPClientSocket.cpp.o:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/ATCPClientSocket.cpp.o
.PHONY : lib/SNetwork/src/ATCPClientSocket.cpp.o

lib/SNetwork/src/ATCPClientSocket.i: lib/SNetwork/src/ATCPClientSocket.cpp.i
.PHONY : lib/SNetwork/src/ATCPClientSocket.i

# target to preprocess a source file
lib/SNetwork/src/ATCPClientSocket.cpp.i:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/ATCPClientSocket.cpp.i
.PHONY : lib/SNetwork/src/ATCPClientSocket.cpp.i

lib/SNetwork/src/ATCPClientSocket.s: lib/SNetwork/src/ATCPClientSocket.cpp.s
.PHONY : lib/SNetwork/src/ATCPClientSocket.s

# target to generate assembly for a file
lib/SNetwork/src/ATCPClientSocket.cpp.s:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/ATCPClientSocket.cpp.s
.PHONY : lib/SNetwork/src/ATCPClientSocket.cpp.s

lib/SNetwork/src/ATCPServerSocket.o: lib/SNetwork/src/ATCPServerSocket.cpp.o
.PHONY : lib/SNetwork/src/ATCPServerSocket.o

# target to build an object file
lib/SNetwork/src/ATCPServerSocket.cpp.o:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/ATCPServerSocket.cpp.o
.PHONY : lib/SNetwork/src/ATCPServerSocket.cpp.o

lib/SNetwork/src/ATCPServerSocket.i: lib/SNetwork/src/ATCPServerSocket.cpp.i
.PHONY : lib/SNetwork/src/ATCPServerSocket.i

# target to preprocess a source file
lib/SNetwork/src/ATCPServerSocket.cpp.i:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/ATCPServerSocket.cpp.i
.PHONY : lib/SNetwork/src/ATCPServerSocket.cpp.i

lib/SNetwork/src/ATCPServerSocket.s: lib/SNetwork/src/ATCPServerSocket.cpp.s
.PHONY : lib/SNetwork/src/ATCPServerSocket.s

# target to generate assembly for a file
lib/SNetwork/src/ATCPServerSocket.cpp.s:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/ATCPServerSocket.cpp.s
.PHONY : lib/SNetwork/src/ATCPServerSocket.cpp.s

lib/SNetwork/src/TCPClientSocketUnix.o: lib/SNetwork/src/TCPClientSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/TCPClientSocketUnix.o

# target to build an object file
lib/SNetwork/src/TCPClientSocketUnix.cpp.o:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/TCPClientSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/TCPClientSocketUnix.cpp.o

lib/SNetwork/src/TCPClientSocketUnix.i: lib/SNetwork/src/TCPClientSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/TCPClientSocketUnix.i

# target to preprocess a source file
lib/SNetwork/src/TCPClientSocketUnix.cpp.i:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/TCPClientSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/TCPClientSocketUnix.cpp.i

lib/SNetwork/src/TCPClientSocketUnix.s: lib/SNetwork/src/TCPClientSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/TCPClientSocketUnix.s

# target to generate assembly for a file
lib/SNetwork/src/TCPClientSocketUnix.cpp.s:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/TCPClientSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/TCPClientSocketUnix.cpp.s

lib/SNetwork/src/TCPServerSocketUnix.o: lib/SNetwork/src/TCPServerSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/TCPServerSocketUnix.o

# target to build an object file
lib/SNetwork/src/TCPServerSocketUnix.cpp.o:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/TCPServerSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/TCPServerSocketUnix.cpp.o

lib/SNetwork/src/TCPServerSocketUnix.i: lib/SNetwork/src/TCPServerSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/TCPServerSocketUnix.i

# target to preprocess a source file
lib/SNetwork/src/TCPServerSocketUnix.cpp.i:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/TCPServerSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/TCPServerSocketUnix.cpp.i

lib/SNetwork/src/TCPServerSocketUnix.s: lib/SNetwork/src/TCPServerSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/TCPServerSocketUnix.s

# target to generate assembly for a file
lib/SNetwork/src/TCPServerSocketUnix.cpp.s:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/TCPServerSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/TCPServerSocketUnix.cpp.s

lib/SNetwork/src/UDPClientSocketUnix.o: lib/SNetwork/src/UDPClientSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/UDPClientSocketUnix.o

# target to build an object file
lib/SNetwork/src/UDPClientSocketUnix.cpp.o:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/UDPClientSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/UDPClientSocketUnix.cpp.o

lib/SNetwork/src/UDPClientSocketUnix.i: lib/SNetwork/src/UDPClientSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/UDPClientSocketUnix.i

# target to preprocess a source file
lib/SNetwork/src/UDPClientSocketUnix.cpp.i:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/UDPClientSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/UDPClientSocketUnix.cpp.i

lib/SNetwork/src/UDPClientSocketUnix.s: lib/SNetwork/src/UDPClientSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/UDPClientSocketUnix.s

# target to generate assembly for a file
lib/SNetwork/src/UDPClientSocketUnix.cpp.s:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/UDPClientSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/UDPClientSocketUnix.cpp.s

lib/SNetwork/src/UDPServerSocketUnix.o: lib/SNetwork/src/UDPServerSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/UDPServerSocketUnix.o

# target to build an object file
lib/SNetwork/src/UDPServerSocketUnix.cpp.o:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/UDPServerSocketUnix.cpp.o
.PHONY : lib/SNetwork/src/UDPServerSocketUnix.cpp.o

lib/SNetwork/src/UDPServerSocketUnix.i: lib/SNetwork/src/UDPServerSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/UDPServerSocketUnix.i

# target to preprocess a source file
lib/SNetwork/src/UDPServerSocketUnix.cpp.i:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/UDPServerSocketUnix.cpp.i
.PHONY : lib/SNetwork/src/UDPServerSocketUnix.cpp.i

lib/SNetwork/src/UDPServerSocketUnix.s: lib/SNetwork/src/UDPServerSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/UDPServerSocketUnix.s

# target to generate assembly for a file
lib/SNetwork/src/UDPServerSocketUnix.cpp.s:
	$(MAKE) -f CMakeFiles/SNetwork.dir/build.make CMakeFiles/SNetwork.dir/lib/SNetwork/src/UDPServerSocketUnix.cpp.s
.PHONY : lib/SNetwork/src/UDPServerSocketUnix.cpp.s

lib/Thread/src/CondVarUnix.o: lib/Thread/src/CondVarUnix.cpp.o
.PHONY : lib/Thread/src/CondVarUnix.o

# target to build an object file
lib/Thread/src/CondVarUnix.cpp.o:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/CondVarUnix.cpp.o
.PHONY : lib/Thread/src/CondVarUnix.cpp.o

lib/Thread/src/CondVarUnix.i: lib/Thread/src/CondVarUnix.cpp.i
.PHONY : lib/Thread/src/CondVarUnix.i

# target to preprocess a source file
lib/Thread/src/CondVarUnix.cpp.i:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/CondVarUnix.cpp.i
.PHONY : lib/Thread/src/CondVarUnix.cpp.i

lib/Thread/src/CondVarUnix.s: lib/Thread/src/CondVarUnix.cpp.s
.PHONY : lib/Thread/src/CondVarUnix.s

# target to generate assembly for a file
lib/Thread/src/CondVarUnix.cpp.s:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/CondVarUnix.cpp.s
.PHONY : lib/Thread/src/CondVarUnix.cpp.s

lib/Thread/src/MutexUnix.o: lib/Thread/src/MutexUnix.cpp.o
.PHONY : lib/Thread/src/MutexUnix.o

# target to build an object file
lib/Thread/src/MutexUnix.cpp.o:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/MutexUnix.cpp.o
.PHONY : lib/Thread/src/MutexUnix.cpp.o

lib/Thread/src/MutexUnix.i: lib/Thread/src/MutexUnix.cpp.i
.PHONY : lib/Thread/src/MutexUnix.i

# target to preprocess a source file
lib/Thread/src/MutexUnix.cpp.i:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/MutexUnix.cpp.i
.PHONY : lib/Thread/src/MutexUnix.cpp.i

lib/Thread/src/MutexUnix.s: lib/Thread/src/MutexUnix.cpp.s
.PHONY : lib/Thread/src/MutexUnix.s

# target to generate assembly for a file
lib/Thread/src/MutexUnix.cpp.s:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/MutexUnix.cpp.s
.PHONY : lib/Thread/src/MutexUnix.cpp.s

lib/Thread/src/ScopedLock.o: lib/Thread/src/ScopedLock.cpp.o
.PHONY : lib/Thread/src/ScopedLock.o

# target to build an object file
lib/Thread/src/ScopedLock.cpp.o:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/ScopedLock.cpp.o
.PHONY : lib/Thread/src/ScopedLock.cpp.o

lib/Thread/src/ScopedLock.i: lib/Thread/src/ScopedLock.cpp.i
.PHONY : lib/Thread/src/ScopedLock.i

# target to preprocess a source file
lib/Thread/src/ScopedLock.cpp.i:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/ScopedLock.cpp.i
.PHONY : lib/Thread/src/ScopedLock.cpp.i

lib/Thread/src/ScopedLock.s: lib/Thread/src/ScopedLock.cpp.s
.PHONY : lib/Thread/src/ScopedLock.s

# target to generate assembly for a file
lib/Thread/src/ScopedLock.cpp.s:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/ScopedLock.cpp.s
.PHONY : lib/Thread/src/ScopedLock.cpp.s

lib/Thread/src/ThreadUnix.o: lib/Thread/src/ThreadUnix.cpp.o
.PHONY : lib/Thread/src/ThreadUnix.o

# target to build an object file
lib/Thread/src/ThreadUnix.cpp.o:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/ThreadUnix.cpp.o
.PHONY : lib/Thread/src/ThreadUnix.cpp.o

lib/Thread/src/ThreadUnix.i: lib/Thread/src/ThreadUnix.cpp.i
.PHONY : lib/Thread/src/ThreadUnix.i

# target to preprocess a source file
lib/Thread/src/ThreadUnix.cpp.i:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/ThreadUnix.cpp.i
.PHONY : lib/Thread/src/ThreadUnix.cpp.i

lib/Thread/src/ThreadUnix.s: lib/Thread/src/ThreadUnix.cpp.s
.PHONY : lib/Thread/src/ThreadUnix.s

# target to generate assembly for a file
lib/Thread/src/ThreadUnix.cpp.s:
	$(MAKE) -f CMakeFiles/Thread.dir/build.make CMakeFiles/Thread.dir/lib/Thread/src/ThreadUnix.cpp.s
.PHONY : lib/Thread/src/ThreadUnix.cpp.s

src/client/Button.o: src/client/Button.cpp.o
.PHONY : src/client/Button.o

# target to build an object file
src/client/Button.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Button.cpp.o
.PHONY : src/client/Button.cpp.o

src/client/Button.i: src/client/Button.cpp.i
.PHONY : src/client/Button.i

# target to preprocess a source file
src/client/Button.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Button.cpp.i
.PHONY : src/client/Button.cpp.i

src/client/Button.s: src/client/Button.cpp.s
.PHONY : src/client/Button.s

# target to generate assembly for a file
src/client/Button.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Button.cpp.s
.PHONY : src/client/Button.cpp.s

src/client/Client.o: src/client/Client.cpp.o
.PHONY : src/client/Client.o

# target to build an object file
src/client/Client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Client.cpp.o
.PHONY : src/client/Client.cpp.o

src/client/Client.i: src/client/Client.cpp.i
.PHONY : src/client/Client.i

# target to preprocess a source file
src/client/Client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Client.cpp.i
.PHONY : src/client/Client.cpp.i

src/client/Client.s: src/client/Client.cpp.s
.PHONY : src/client/Client.s

# target to generate assembly for a file
src/client/Client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Client.cpp.s
.PHONY : src/client/Client.cpp.s

src/client/ClientNetwork.o: src/client/ClientNetwork.cpp.o
.PHONY : src/client/ClientNetwork.o

# target to build an object file
src/client/ClientNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/ClientNetwork.cpp.o
.PHONY : src/client/ClientNetwork.cpp.o

src/client/ClientNetwork.i: src/client/ClientNetwork.cpp.i
.PHONY : src/client/ClientNetwork.i

# target to preprocess a source file
src/client/ClientNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/ClientNetwork.cpp.i
.PHONY : src/client/ClientNetwork.cpp.i

src/client/ClientNetwork.s: src/client/ClientNetwork.cpp.s
.PHONY : src/client/ClientNetwork.s

# target to generate assembly for a file
src/client/ClientNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/ClientNetwork.cpp.s
.PHONY : src/client/ClientNetwork.cpp.s

src/client/DirectoryManagerUnix.o: src/client/DirectoryManagerUnix.cpp.o
.PHONY : src/client/DirectoryManagerUnix.o

# target to build an object file
src/client/DirectoryManagerUnix.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/DirectoryManagerUnix.cpp.o
.PHONY : src/client/DirectoryManagerUnix.cpp.o

src/client/DirectoryManagerUnix.i: src/client/DirectoryManagerUnix.cpp.i
.PHONY : src/client/DirectoryManagerUnix.i

# target to preprocess a source file
src/client/DirectoryManagerUnix.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/DirectoryManagerUnix.cpp.i
.PHONY : src/client/DirectoryManagerUnix.cpp.i

src/client/DirectoryManagerUnix.s: src/client/DirectoryManagerUnix.cpp.s
.PHONY : src/client/DirectoryManagerUnix.s

# target to generate assembly for a file
src/client/DirectoryManagerUnix.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/DirectoryManagerUnix.cpp.s
.PHONY : src/client/DirectoryManagerUnix.cpp.s

src/client/DlLoader.o: src/client/DlLoader.cpp.o
.PHONY : src/client/DlLoader.o

# target to build an object file
src/client/DlLoader.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/DlLoader.cpp.o
.PHONY : src/client/DlLoader.cpp.o

src/client/DlLoader.i: src/client/DlLoader.cpp.i
.PHONY : src/client/DlLoader.i

# target to preprocess a source file
src/client/DlLoader.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/DlLoader.cpp.i
.PHONY : src/client/DlLoader.cpp.i

src/client/DlLoader.s: src/client/DlLoader.cpp.s
.PHONY : src/client/DlLoader.s

# target to generate assembly for a file
src/client/DlLoader.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/DlLoader.cpp.s
.PHONY : src/client/DlLoader.cpp.s

src/client/Dll.o: src/client/Dll.cpp.o
.PHONY : src/client/Dll.o

# target to build an object file
src/client/Dll.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Dll.cpp.o
.PHONY : src/client/Dll.cpp.o

src/client/Dll.i: src/client/Dll.cpp.i
.PHONY : src/client/Dll.i

# target to preprocess a source file
src/client/Dll.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Dll.cpp.i
.PHONY : src/client/Dll.cpp.i

src/client/Dll.s: src/client/Dll.cpp.s
.PHONY : src/client/Dll.s

# target to generate assembly for a file
src/client/Dll.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Dll.cpp.s
.PHONY : src/client/Dll.cpp.s

src/client/Error.o: src/client/Error.cpp.o
.PHONY : src/client/Error.o

# target to build an object file
src/client/Error.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Error.cpp.o
.PHONY : src/client/Error.cpp.o

src/client/Error.i: src/client/Error.cpp.i
.PHONY : src/client/Error.i

# target to preprocess a source file
src/client/Error.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Error.cpp.i
.PHONY : src/client/Error.cpp.i

src/client/Error.s: src/client/Error.cpp.s
.PHONY : src/client/Error.s

# target to generate assembly for a file
src/client/Error.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Error.cpp.s
.PHONY : src/client/Error.cpp.s

src/client/ExtensionSo.o: src/client/ExtensionSo.cpp.o
.PHONY : src/client/ExtensionSo.o

# target to build an object file
src/client/ExtensionSo.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/ExtensionSo.cpp.o
.PHONY : src/client/ExtensionSo.cpp.o

src/client/ExtensionSo.i: src/client/ExtensionSo.cpp.i
.PHONY : src/client/ExtensionSo.i

# target to preprocess a source file
src/client/ExtensionSo.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/ExtensionSo.cpp.i
.PHONY : src/client/ExtensionSo.cpp.i

src/client/ExtensionSo.s: src/client/ExtensionSo.cpp.s
.PHONY : src/client/ExtensionSo.s

# target to generate assembly for a file
src/client/ExtensionSo.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/ExtensionSo.cpp.s
.PHONY : src/client/ExtensionSo.cpp.s

src/client/GraphicClientState.o: src/client/GraphicClientState.cpp.o
.PHONY : src/client/GraphicClientState.o

# target to build an object file
src/client/GraphicClientState.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/GraphicClientState.cpp.o
.PHONY : src/client/GraphicClientState.cpp.o

src/client/GraphicClientState.i: src/client/GraphicClientState.cpp.i
.PHONY : src/client/GraphicClientState.i

# target to preprocess a source file
src/client/GraphicClientState.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/GraphicClientState.cpp.i
.PHONY : src/client/GraphicClientState.cpp.i

src/client/GraphicClientState.s: src/client/GraphicClientState.cpp.s
.PHONY : src/client/GraphicClientState.s

# target to generate assembly for a file
src/client/GraphicClientState.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/GraphicClientState.cpp.s
.PHONY : src/client/GraphicClientState.cpp.s

src/client/MyMusic.o: src/client/MyMusic.cpp.o
.PHONY : src/client/MyMusic.o

# target to build an object file
src/client/MyMusic.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MyMusic.cpp.o
.PHONY : src/client/MyMusic.cpp.o

src/client/MyMusic.i: src/client/MyMusic.cpp.i
.PHONY : src/client/MyMusic.i

# target to preprocess a source file
src/client/MyMusic.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MyMusic.cpp.i
.PHONY : src/client/MyMusic.cpp.i

src/client/MyMusic.s: src/client/MyMusic.cpp.s
.PHONY : src/client/MyMusic.s

# target to generate assembly for a file
src/client/MyMusic.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MyMusic.cpp.s
.PHONY : src/client/MyMusic.cpp.s

src/client/MySound.o: src/client/MySound.cpp.o
.PHONY : src/client/MySound.o

# target to build an object file
src/client/MySound.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MySound.cpp.o
.PHONY : src/client/MySound.cpp.o

src/client/MySound.i: src/client/MySound.cpp.i
.PHONY : src/client/MySound.i

# target to preprocess a source file
src/client/MySound.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MySound.cpp.i
.PHONY : src/client/MySound.cpp.i

src/client/MySound.s: src/client/MySound.cpp.s
.PHONY : src/client/MySound.s

# target to generate assembly for a file
src/client/MySound.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/MySound.cpp.s
.PHONY : src/client/MySound.cpp.s

src/client/Sfml.o: src/client/Sfml.cpp.o
.PHONY : src/client/Sfml.o

# target to build an object file
src/client/Sfml.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Sfml.cpp.o
.PHONY : src/client/Sfml.cpp.o

src/client/Sfml.i: src/client/Sfml.cpp.i
.PHONY : src/client/Sfml.i

# target to preprocess a source file
src/client/Sfml.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Sfml.cpp.i
.PHONY : src/client/Sfml.cpp.i

src/client/Sfml.s: src/client/Sfml.cpp.s
.PHONY : src/client/Sfml.s

# target to generate assembly for a file
src/client/Sfml.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/Sfml.cpp.s
.PHONY : src/client/Sfml.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/protocol/PacketData.o: src/protocol/PacketData.cpp.o
.PHONY : src/protocol/PacketData.o

# target to build an object file
src/protocol/PacketData.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/protocol/PacketData.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketData.cpp.o
.PHONY : src/protocol/PacketData.cpp.o

src/protocol/PacketData.i: src/protocol/PacketData.cpp.i
.PHONY : src/protocol/PacketData.i

# target to preprocess a source file
src/protocol/PacketData.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/protocol/PacketData.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketData.cpp.i
.PHONY : src/protocol/PacketData.cpp.i

src/protocol/PacketData.s: src/protocol/PacketData.cpp.s
.PHONY : src/protocol/PacketData.s

# target to generate assembly for a file
src/protocol/PacketData.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/protocol/PacketData.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketData.cpp.s
.PHONY : src/protocol/PacketData.cpp.s

src/protocol/PacketFactory.o: src/protocol/PacketFactory.cpp.o
.PHONY : src/protocol/PacketFactory.o

# target to build an object file
src/protocol/PacketFactory.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/protocol/PacketFactory.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketFactory.cpp.o
.PHONY : src/protocol/PacketFactory.cpp.o

src/protocol/PacketFactory.i: src/protocol/PacketFactory.cpp.i
.PHONY : src/protocol/PacketFactory.i

# target to preprocess a source file
src/protocol/PacketFactory.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/protocol/PacketFactory.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketFactory.cpp.i
.PHONY : src/protocol/PacketFactory.cpp.i

src/protocol/PacketFactory.s: src/protocol/PacketFactory.cpp.s
.PHONY : src/protocol/PacketFactory.s

# target to generate assembly for a file
src/protocol/PacketFactory.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/protocol/PacketFactory.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketFactory.cpp.s
.PHONY : src/protocol/PacketFactory.cpp.s

src/protocol/PacketManager.o: src/protocol/PacketManager.cpp.o
.PHONY : src/protocol/PacketManager.o

# target to build an object file
src/protocol/PacketManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketManager.cpp.o
.PHONY : src/protocol/PacketManager.cpp.o

src/protocol/PacketManager.i: src/protocol/PacketManager.cpp.i
.PHONY : src/protocol/PacketManager.i

# target to preprocess a source file
src/protocol/PacketManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketManager.cpp.i
.PHONY : src/protocol/PacketManager.cpp.i

src/protocol/PacketManager.s: src/protocol/PacketManager.cpp.s
.PHONY : src/protocol/PacketManager.s

# target to generate assembly for a file
src/protocol/PacketManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/PacketManager.cpp.s
.PHONY : src/protocol/PacketManager.cpp.s

src/protocol/actions/ProtocolGame.o: src/protocol/actions/ProtocolGame.cpp.o
.PHONY : src/protocol/actions/ProtocolGame.o

# target to build an object file
src/protocol/actions/ProtocolGame.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolGame.cpp.o
.PHONY : src/protocol/actions/ProtocolGame.cpp.o

src/protocol/actions/ProtocolGame.i: src/protocol/actions/ProtocolGame.cpp.i
.PHONY : src/protocol/actions/ProtocolGame.i

# target to preprocess a source file
src/protocol/actions/ProtocolGame.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolGame.cpp.i
.PHONY : src/protocol/actions/ProtocolGame.cpp.i

src/protocol/actions/ProtocolGame.s: src/protocol/actions/ProtocolGame.cpp.s
.PHONY : src/protocol/actions/ProtocolGame.s

# target to generate assembly for a file
src/protocol/actions/ProtocolGame.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolGame.cpp.s
.PHONY : src/protocol/actions/ProtocolGame.cpp.s

src/protocol/actions/ProtocolGameDetails.o: src/protocol/actions/ProtocolGameDetails.cpp.o
.PHONY : src/protocol/actions/ProtocolGameDetails.o

# target to build an object file
src/protocol/actions/ProtocolGameDetails.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolGameDetails.cpp.o
.PHONY : src/protocol/actions/ProtocolGameDetails.cpp.o

src/protocol/actions/ProtocolGameDetails.i: src/protocol/actions/ProtocolGameDetails.cpp.i
.PHONY : src/protocol/actions/ProtocolGameDetails.i

# target to preprocess a source file
src/protocol/actions/ProtocolGameDetails.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolGameDetails.cpp.i
.PHONY : src/protocol/actions/ProtocolGameDetails.cpp.i

src/protocol/actions/ProtocolGameDetails.s: src/protocol/actions/ProtocolGameDetails.cpp.s
.PHONY : src/protocol/actions/ProtocolGameDetails.s

# target to generate assembly for a file
src/protocol/actions/ProtocolGameDetails.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolGameDetails.cpp.s
.PHONY : src/protocol/actions/ProtocolGameDetails.cpp.s

src/protocol/actions/ProtocolLobby.o: src/protocol/actions/ProtocolLobby.cpp.o
.PHONY : src/protocol/actions/ProtocolLobby.o

# target to build an object file
src/protocol/actions/ProtocolLobby.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolLobby.cpp.o
.PHONY : src/protocol/actions/ProtocolLobby.cpp.o

src/protocol/actions/ProtocolLobby.i: src/protocol/actions/ProtocolLobby.cpp.i
.PHONY : src/protocol/actions/ProtocolLobby.i

# target to preprocess a source file
src/protocol/actions/ProtocolLobby.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolLobby.cpp.i
.PHONY : src/protocol/actions/ProtocolLobby.cpp.i

src/protocol/actions/ProtocolLobby.s: src/protocol/actions/ProtocolLobby.cpp.s
.PHONY : src/protocol/actions/ProtocolLobby.s

# target to generate assembly for a file
src/protocol/actions/ProtocolLobby.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolLobby.cpp.s
.PHONY : src/protocol/actions/ProtocolLobby.cpp.s

src/protocol/actions/ProtocolMovement.o: src/protocol/actions/ProtocolMovement.cpp.o
.PHONY : src/protocol/actions/ProtocolMovement.o

# target to build an object file
src/protocol/actions/ProtocolMovement.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolMovement.cpp.o
.PHONY : src/protocol/actions/ProtocolMovement.cpp.o

src/protocol/actions/ProtocolMovement.i: src/protocol/actions/ProtocolMovement.cpp.i
.PHONY : src/protocol/actions/ProtocolMovement.i

# target to preprocess a source file
src/protocol/actions/ProtocolMovement.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolMovement.cpp.i
.PHONY : src/protocol/actions/ProtocolMovement.cpp.i

src/protocol/actions/ProtocolMovement.s: src/protocol/actions/ProtocolMovement.cpp.s
.PHONY : src/protocol/actions/ProtocolMovement.s

# target to generate assembly for a file
src/protocol/actions/ProtocolMovement.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/protocol/actions/ProtocolMovement.cpp.s
.PHONY : src/protocol/actions/ProtocolMovement.cpp.s

src/server/Game.o: src/server/Game.cpp.o
.PHONY : src/server/Game.o

# target to build an object file
src/server/Game.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Game.cpp.o
.PHONY : src/server/Game.cpp.o

src/server/Game.i: src/server/Game.cpp.i
.PHONY : src/server/Game.i

# target to preprocess a source file
src/server/Game.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Game.cpp.i
.PHONY : src/server/Game.cpp.i

src/server/Game.s: src/server/Game.cpp.s
.PHONY : src/server/Game.s

# target to generate assembly for a file
src/server/Game.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Game.cpp.s
.PHONY : src/server/Game.cpp.s

src/server/GameManager.o: src/server/GameManager.cpp.o
.PHONY : src/server/GameManager.o

# target to build an object file
src/server/GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/GameManager.cpp.o
.PHONY : src/server/GameManager.cpp.o

src/server/GameManager.i: src/server/GameManager.cpp.i
.PHONY : src/server/GameManager.i

# target to preprocess a source file
src/server/GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/GameManager.cpp.i
.PHONY : src/server/GameManager.cpp.i

src/server/GameManager.s: src/server/GameManager.cpp.s
.PHONY : src/server/GameManager.s

# target to generate assembly for a file
src/server/GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/GameManager.cpp.s
.PHONY : src/server/GameManager.cpp.s

src/server/PacketAggregator.o: src/server/PacketAggregator.cpp.o
.PHONY : src/server/PacketAggregator.o

# target to build an object file
src/server/PacketAggregator.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/server/PacketAggregator.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PacketAggregator.cpp.o
.PHONY : src/server/PacketAggregator.cpp.o

src/server/PacketAggregator.i: src/server/PacketAggregator.cpp.i
.PHONY : src/server/PacketAggregator.i

# target to preprocess a source file
src/server/PacketAggregator.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/server/PacketAggregator.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PacketAggregator.cpp.i
.PHONY : src/server/PacketAggregator.cpp.i

src/server/PacketAggregator.s: src/server/PacketAggregator.cpp.s
.PHONY : src/server/PacketAggregator.s

# target to generate assembly for a file
src/server/PacketAggregator.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/server/PacketAggregator.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PacketAggregator.cpp.s
.PHONY : src/server/PacketAggregator.cpp.s

src/server/PacketTask.o: src/server/PacketTask.cpp.o
.PHONY : src/server/PacketTask.o

# target to build an object file
src/server/PacketTask.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PacketTask.cpp.o
.PHONY : src/server/PacketTask.cpp.o

src/server/PacketTask.i: src/server/PacketTask.cpp.i
.PHONY : src/server/PacketTask.i

# target to preprocess a source file
src/server/PacketTask.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PacketTask.cpp.i
.PHONY : src/server/PacketTask.cpp.i

src/server/PacketTask.s: src/server/PacketTask.cpp.s
.PHONY : src/server/PacketTask.s

# target to generate assembly for a file
src/server/PacketTask.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PacketTask.cpp.s
.PHONY : src/server/PacketTask.cpp.s

src/server/SafeQueue.o: src/server/SafeQueue.cpp.o
.PHONY : src/server/SafeQueue.o

# target to build an object file
src/server/SafeQueue.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/SafeQueue.cpp.o
.PHONY : src/server/SafeQueue.cpp.o

src/server/SafeQueue.i: src/server/SafeQueue.cpp.i
.PHONY : src/server/SafeQueue.i

# target to preprocess a source file
src/server/SafeQueue.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/SafeQueue.cpp.i
.PHONY : src/server/SafeQueue.cpp.i

src/server/SafeQueue.s: src/server/SafeQueue.cpp.s
.PHONY : src/server/SafeQueue.s

# target to generate assembly for a file
src/server/SafeQueue.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/SafeQueue.cpp.s
.PHONY : src/server/SafeQueue.cpp.s

src/server/Server.o: src/server/Server.cpp.o
.PHONY : src/server/Server.o

# target to build an object file
src/server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Server.cpp.o
.PHONY : src/server/Server.cpp.o

src/server/Server.i: src/server/Server.cpp.i
.PHONY : src/server/Server.i

# target to preprocess a source file
src/server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Server.cpp.i
.PHONY : src/server/Server.cpp.i

src/server/Server.s: src/server/Server.cpp.s
.PHONY : src/server/Server.s

# target to generate assembly for a file
src/server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Server.cpp.s
.PHONY : src/server/Server.cpp.s

src/server/TaskManager.o: src/server/TaskManager.cpp.o
.PHONY : src/server/TaskManager.o

# target to build an object file
src/server/TaskManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/TaskManager.cpp.o
.PHONY : src/server/TaskManager.cpp.o

src/server/TaskManager.i: src/server/TaskManager.cpp.i
.PHONY : src/server/TaskManager.i

# target to preprocess a source file
src/server/TaskManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/TaskManager.cpp.i
.PHONY : src/server/TaskManager.cpp.i

src/server/TaskManager.s: src/server/TaskManager.cpp.s
.PHONY : src/server/TaskManager.s

# target to generate assembly for a file
src/server/TaskManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/TaskManager.cpp.s
.PHONY : src/server/TaskManager.cpp.s

src/server/TaskNetwork.o: src/server/TaskNetwork.cpp.o
.PHONY : src/server/TaskNetwork.o

# target to build an object file
src/server/TaskNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/TaskNetwork.cpp.o
.PHONY : src/server/TaskNetwork.cpp.o

src/server/TaskNetwork.i: src/server/TaskNetwork.cpp.i
.PHONY : src/server/TaskNetwork.i

# target to preprocess a source file
src/server/TaskNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/TaskNetwork.cpp.i
.PHONY : src/server/TaskNetwork.cpp.i

src/server/TaskNetwork.s: src/server/TaskNetwork.cpp.s
.PHONY : src/server/TaskNetwork.s

# target to generate assembly for a file
src/server/TaskNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/TaskNetwork.cpp.s
.PHONY : src/server/TaskNetwork.cpp.s

src/server/ThreadData.o: src/server/ThreadData.cpp.o
.PHONY : src/server/ThreadData.o

# target to build an object file
src/server/ThreadData.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadData.cpp.o
.PHONY : src/server/ThreadData.cpp.o

src/server/ThreadData.i: src/server/ThreadData.cpp.i
.PHONY : src/server/ThreadData.i

# target to preprocess a source file
src/server/ThreadData.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadData.cpp.i
.PHONY : src/server/ThreadData.cpp.i

src/server/ThreadData.s: src/server/ThreadData.cpp.s
.PHONY : src/server/ThreadData.s

# target to generate assembly for a file
src/server/ThreadData.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadData.cpp.s
.PHONY : src/server/ThreadData.cpp.s

src/server/ThreadPool.o: src/server/ThreadPool.cpp.o
.PHONY : src/server/ThreadPool.o

# target to build an object file
src/server/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadPool.cpp.o
.PHONY : src/server/ThreadPool.cpp.o

src/server/ThreadPool.i: src/server/ThreadPool.cpp.i
.PHONY : src/server/ThreadPool.i

# target to preprocess a source file
src/server/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadPool.cpp.i
.PHONY : src/server/ThreadPool.cpp.i

src/server/ThreadPool.s: src/server/ThreadPool.cpp.s
.PHONY : src/server/ThreadPool.s

# target to generate assembly for a file
src/server/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadPool.cpp.s
.PHONY : src/server/ThreadPool.cpp.s

src/server/User.o: src/server/User.cpp.o
.PHONY : src/server/User.o

# target to build an object file
src/server/User.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/User.cpp.o
.PHONY : src/server/User.cpp.o

src/server/User.i: src/server/User.cpp.i
.PHONY : src/server/User.i

# target to preprocess a source file
src/server/User.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/User.cpp.i
.PHONY : src/server/User.cpp.i

src/server/User.s: src/server/User.cpp.s
.PHONY : src/server/User.s

# target to generate assembly for a file
src/server/User.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/User.cpp.s
.PHONY : src/server/User.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SNetwork"
	@echo "... Thread"
	@echo "... client"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... lib/SNetwork/src/ATCPClientSocket.o"
	@echo "... lib/SNetwork/src/ATCPClientSocket.i"
	@echo "... lib/SNetwork/src/ATCPClientSocket.s"
	@echo "... lib/SNetwork/src/ATCPServerSocket.o"
	@echo "... lib/SNetwork/src/ATCPServerSocket.i"
	@echo "... lib/SNetwork/src/ATCPServerSocket.s"
	@echo "... lib/SNetwork/src/TCPClientSocketUnix.o"
	@echo "... lib/SNetwork/src/TCPClientSocketUnix.i"
	@echo "... lib/SNetwork/src/TCPClientSocketUnix.s"
	@echo "... lib/SNetwork/src/TCPServerSocketUnix.o"
	@echo "... lib/SNetwork/src/TCPServerSocketUnix.i"
	@echo "... lib/SNetwork/src/TCPServerSocketUnix.s"
	@echo "... lib/SNetwork/src/UDPClientSocketUnix.o"
	@echo "... lib/SNetwork/src/UDPClientSocketUnix.i"
	@echo "... lib/SNetwork/src/UDPClientSocketUnix.s"
	@echo "... lib/SNetwork/src/UDPServerSocketUnix.o"
	@echo "... lib/SNetwork/src/UDPServerSocketUnix.i"
	@echo "... lib/SNetwork/src/UDPServerSocketUnix.s"
	@echo "... lib/Thread/src/CondVarUnix.o"
	@echo "... lib/Thread/src/CondVarUnix.i"
	@echo "... lib/Thread/src/CondVarUnix.s"
	@echo "... lib/Thread/src/MutexUnix.o"
	@echo "... lib/Thread/src/MutexUnix.i"
	@echo "... lib/Thread/src/MutexUnix.s"
	@echo "... lib/Thread/src/ScopedLock.o"
	@echo "... lib/Thread/src/ScopedLock.i"
	@echo "... lib/Thread/src/ScopedLock.s"
	@echo "... lib/Thread/src/ThreadUnix.o"
	@echo "... lib/Thread/src/ThreadUnix.i"
	@echo "... lib/Thread/src/ThreadUnix.s"
	@echo "... src/client/Button.o"
	@echo "... src/client/Button.i"
	@echo "... src/client/Button.s"
	@echo "... src/client/Client.o"
	@echo "... src/client/Client.i"
	@echo "... src/client/Client.s"
	@echo "... src/client/ClientNetwork.o"
	@echo "... src/client/ClientNetwork.i"
	@echo "... src/client/ClientNetwork.s"
	@echo "... src/client/DirectoryManagerUnix.o"
	@echo "... src/client/DirectoryManagerUnix.i"
	@echo "... src/client/DirectoryManagerUnix.s"
	@echo "... src/client/DlLoader.o"
	@echo "... src/client/DlLoader.i"
	@echo "... src/client/DlLoader.s"
	@echo "... src/client/Dll.o"
	@echo "... src/client/Dll.i"
	@echo "... src/client/Dll.s"
	@echo "... src/client/Error.o"
	@echo "... src/client/Error.i"
	@echo "... src/client/Error.s"
	@echo "... src/client/ExtensionSo.o"
	@echo "... src/client/ExtensionSo.i"
	@echo "... src/client/ExtensionSo.s"
	@echo "... src/client/GraphicClientState.o"
	@echo "... src/client/GraphicClientState.i"
	@echo "... src/client/GraphicClientState.s"
	@echo "... src/client/MyMusic.o"
	@echo "... src/client/MyMusic.i"
	@echo "... src/client/MyMusic.s"
	@echo "... src/client/MySound.o"
	@echo "... src/client/MySound.i"
	@echo "... src/client/MySound.s"
	@echo "... src/client/Sfml.o"
	@echo "... src/client/Sfml.i"
	@echo "... src/client/Sfml.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/protocol/PacketData.o"
	@echo "... src/protocol/PacketData.i"
	@echo "... src/protocol/PacketData.s"
	@echo "... src/protocol/PacketFactory.o"
	@echo "... src/protocol/PacketFactory.i"
	@echo "... src/protocol/PacketFactory.s"
	@echo "... src/protocol/PacketManager.o"
	@echo "... src/protocol/PacketManager.i"
	@echo "... src/protocol/PacketManager.s"
	@echo "... src/protocol/actions/ProtocolGame.o"
	@echo "... src/protocol/actions/ProtocolGame.i"
	@echo "... src/protocol/actions/ProtocolGame.s"
	@echo "... src/protocol/actions/ProtocolGameDetails.o"
	@echo "... src/protocol/actions/ProtocolGameDetails.i"
	@echo "... src/protocol/actions/ProtocolGameDetails.s"
	@echo "... src/protocol/actions/ProtocolLobby.o"
	@echo "... src/protocol/actions/ProtocolLobby.i"
	@echo "... src/protocol/actions/ProtocolLobby.s"
	@echo "... src/protocol/actions/ProtocolMovement.o"
	@echo "... src/protocol/actions/ProtocolMovement.i"
	@echo "... src/protocol/actions/ProtocolMovement.s"
	@echo "... src/server/Game.o"
	@echo "... src/server/Game.i"
	@echo "... src/server/Game.s"
	@echo "... src/server/GameManager.o"
	@echo "... src/server/GameManager.i"
	@echo "... src/server/GameManager.s"
	@echo "... src/server/PacketAggregator.o"
	@echo "... src/server/PacketAggregator.i"
	@echo "... src/server/PacketAggregator.s"
	@echo "... src/server/PacketTask.o"
	@echo "... src/server/PacketTask.i"
	@echo "... src/server/PacketTask.s"
	@echo "... src/server/SafeQueue.o"
	@echo "... src/server/SafeQueue.i"
	@echo "... src/server/SafeQueue.s"
	@echo "... src/server/Server.o"
	@echo "... src/server/Server.i"
	@echo "... src/server/Server.s"
	@echo "... src/server/TaskManager.o"
	@echo "... src/server/TaskManager.i"
	@echo "... src/server/TaskManager.s"
	@echo "... src/server/TaskNetwork.o"
	@echo "... src/server/TaskNetwork.i"
	@echo "... src/server/TaskNetwork.s"
	@echo "... src/server/ThreadData.o"
	@echo "... src/server/ThreadData.i"
	@echo "... src/server/ThreadData.s"
	@echo "... src/server/ThreadPool.o"
	@echo "... src/server/ThreadPool.i"
	@echo "... src/server/ThreadPool.s"
	@echo "... src/server/User.o"
	@echo "... src/server/User.i"
	@echo "... src/server/User.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

