#ifndef __EPROTOCOLPACKET_MOVEMENT_HPP_
#define __EPROTOCOLPACKET_MOVEMENT_HPP_

enum		eProtocolPacketMovement
  {
    MOVE		= 0,
    UPDATEPLAYER	= 1,
    UPDATEENEMY		= 2,
    UPDATEBULLET	= 3,
    NEWBULLET		= 4,
    MOVEMENT_MAX	= 5,
    MOVEMENT_ERROR
  };

#endif // __EPROTOCOLPACKET_MOVEMENT_HPP_
