#ifndef		__EPROTOCOLPACKETPOSITION_HPP__
# define	__EPROTOCOLPACKETPOSITION_HPP__

enum		eProtocolPacketPosition
  {
    POSITION_ERROR,
    MOVE_PLAYER,
    UPDATE_PLAYER,
    UPDATE_ENEMY,
    UPDATE_BULLETS,
    NEW_BULLET,
    POSITION_MAX,
  };

#endif		/*__EPROTOCOLPACKETPOSITION_HPP__*/
