# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = R-Type_Features.pdf

# List the files included in the slides
DEPS =

# Relative path to the LaTeX koala documentclass setup files
# You should not need to touch this
RELPATH = ../class

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
